### ISSUE TITLE
ACI shared library Idempotency

### ISSUE THREAD

**Issue by schunduri** [datacenter/aci-ansible#15]
If you perform a Get or Query against a deleted object and APIC returns a 200 response status and an empty response data. When running the playbook shouldn't that either fail or show a message that says object doesn't exist?

**Comment by dagwieers** [comment]
@schunduri Yes, you are right. Integration tests will catch this too.

**Comment by dagwieers** [comment]
Not an issue, works as designed. A query or get should not cause the task to fail.
