### ISSUE TITLE
Define URL maps for ACI classes as part of the module

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#150]
It would be nice if the parts that are now listed in the URL_MAPPING data-structure would be defined as part of the module, rather than shared. I do understand the value of having this shared, but

- it makes it impossible for external modules to use our ACI framework
- it limits what is possible as it seems depending on parameters provided the URI would be (very) different (see: https://developer.cisco.com/media/mim-ref/MO-fvnsEncapBlk.html as example)

I think it would be nice to have an in-person discussion on this, because I don't think I understand all the implications :-)

**Comment by jmcgill298** [comment]
We should discuss this week in SF. My short response:
1) Not exactly sure what you mean, or what you are looking to extend this to.
2) I think the URLs listed in the MIM are causing confusion, the module should only be concerned with `uni/infra/{encap type}-[name]/from-[number]-to-[number]`. Assuming you wanted to support all encap types with one module, then the module would need a parameter `encap_type`, which would look something like this:
```
encap_type = module.param['encap_type]
aci.construct_url(root_class=encap_type, subclass_1='encap_from_to')
```

**Comment by dagwieers** [comment]
Thanks @jmcgill298 !
