### ISSUE TITLE
In aci_bd_subnet, 'scope' needs to support multiple parameters at once

### ISSUE THREAD

**Issue by nilloBE** [datacenter/aci-ansible#162]
The module aci_bd_subnet has an attribute 'scope' that allows to specify if a subnet should be kept private to a VRF, or if it should be advertised and potentially shared. There are therefore three options: public, private and shared. Public and Private are mutually exclusive, but 'shared' can be present with either of them. 

We need to add the possibility of adding:

scope: "public,shared"
or
scope: "private,share"

in addition to public and private being the only setting.

**Comment by dagwieers** [comment]
@nilloBE I pushed a quick fix that can be back-ported to stable-2.4, but I am looking to improve the support in Ansible for lists with fixed sets of options.

**Comment by jmcgill298** [comment]
https://github.com/datacenter/aci-ansible/pull/171
