### ISSUE TITLE
Module aci_epg_to_domain does not need to support OpenStack

### ISSUE THREAD

**Issue by nilloBE** [datacenter/aci-ansible#163]
The module aci_epg_to_domain allows mapping an EPG to a Physical or Virtual Domain in ACI. The Virtual Domain allows the user to specify the domain type selecting VMware, Microsoft or OpenStack.

In this setting, OpenStack should be removed because the OpenStack EPGs should not be created or manipulated directly via Ansible, but instead via Neutron.

**Comment by jmcgill298** [comment]
@nilloBE regardless of what people should configure, does the module support invalid API requests to the APIC?

**Comment by nilloBE** [comment]
The module does not support invalid API requests. You can actually through this module map an EPG to an OpenStack domain, from an API perspective this is not an invalid request. But the EPG will not exists in neutron DB unless it is created by neutron, and therefore it will not be usable at all by the OpenStack workloads. With OpenStack, users must leverage neutron API which will in turn create EPGs on the ACI fabric and automatically map them to the right VMM domain.

**Comment by jmcgill298** [comment]
If ACI supports something that is invalid, then I would put that on Cisco needs to remove the feature. If they are supporting it, then I would rather assume that someone is using it, or that Cisco has plans to make it useful.

**Comment by dagwieers** [comment]
@nilloBE I think the better approach here is to add notes to the documentation of the module to clarify what is expected for this specific use-case. And leave the functionality in the module.

Can you propose the exact wording for the note in the module ?

**Comment by dagwieers** [comment]
This issue was moved to ansible/ansible#34211
