### ISSUE TITLE
Some modules include references to non-existing modules

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#178]
So some of the modules we have refer to yet non-existing modules from the documentation, e.g. aci_l3out.

Not necessarily a problem, but the documentation toolchain complains about these at the moment.

What do we do ?

**Comment by jmcgill298** [comment]
@dagwieers what module is referred to in aci_l3out that does not exist?

**Comment by dagwieers** [comment]
@jmcgill298 So the complaint was that in this document: https://docs.ansible.com/ansible/devel/aci_bd_to_l3out_module.html there is a reference to the aci_l3out module, which does not exist yet.

**Comment by jmcgill298** [comment]
okay, so on the ansible repo. I see that the `aci_l3out` module in this repo is actually the older version of `aci_bd_to_l3out`. However, there really should be a module that manages l3outs. I guess we shouldn't point to a module that doesn't exist though, so either we need to create the module soon, or point people to aci_rest for l3out creations.

**Comment by dagwieers** [comment]
Yeah, I am torn as we risk never updating the docs of the existing modules once we have those modules added. However the **aci_l3out** module was a low-priority module (based on the fact it's not a common operation). I can't prevent someone else writing it though ;-)

**Comment by dagwieers** [comment]
Moving this to the action plan.
