### ISSUE TITLE
customize BD mac-address

### ISSUE THREAD

**Issue by bmfernand** [datacenter/aci-ansible#181]
Hello Guys,

From module "aci_bd" I see no option to customize "mac_address" from a bridge-domain .... so the current option for doing this is only trough "aci_rest" module ?

For migration purposes it's sometimes nice to keep the same MAC so I guess this would be a nice to have on "aci_bd" module :)

Thanks and Regards
Bruno

**Comment by dagwieers** [comment]
Hi @bmfernand 

We are no longer tracking issues on this repository, but directly upstream. Could you open a new issue on https://github.com/ansible/ansible/issues/new ?

Thanks in advance !
