### ISSUE TITLE
Scope must allow multiple choices

### ISSUE THREAD

**Issue by nilloBE** [datacenter/aci-ansible#182]
At the moment the scope must be set to one of public, private or shared. However some combinations are possible:
- public means subnet is advertised on L3Out
- private means subnet is not advertised on L3Out
- shared means subnet can be shared to other VRFs

There are subnets that can be:
- public and shared
- private and shared

We need to modify scope to accept multiple values. At the moment when selecting multiple values we get an error:
fatal: [apic-troy-1]: FAILED! => {"changed": false, "failed": true, "msg": "value of scope must be one of: private,public,shared, got: public,shared"}

But public,shared and private,shared should be acceptable.

**Comment by jmcgill298** [comment]
@nilloBE I'm assuming you are referring to the `aco_bd_subnet` module; that was patched in November. It accepts: private, public, shared, or a list containing either private or public with shared

**Comment by dagwieers** [comment]
Yup, see #162, opened by yourself ;-)

**Comment by dagwieers** [comment]
PS We are no longer working on this repository, please open issue tickets at https://github.com/ansible/ansible/issues/new instead !
