### ISSUE TITLE
Implement booleans as 'enabled'/'disabled'

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#26]
I would prefer if we would add booleans for some parameters (see aci_lldp_interface_policy) and translate these automatically to the strings enabled/disabled.

We would have to do the same for integer types, that need to become strings.

**Comment by schunduri** [comment]
Noted

**Comment by dagwieers** [comment]
Since we now have yes/no strings s booleans as well, I don't think we can assume enabled/disabled should be a default. Or at least one should be able to tell that in specific cases the default is yes/no instead.

Would be nice to have a break down of what's used most. Or have a discussion with ACI developers to understand the backend model driving this.

**Comment by dagwieers** [comment]
No longer valid. Closing.
