### ISSUE TITLE
Use required_if

### ISSUE THREAD

**Issue by jmcgill298** [datacenter/aci-ansible#55]
In order to simplify the logic to build the proper path for the API request, we can use the required_if when calling AnsibleModule.
```
required_if = [['state', 'present', ['object_id', 'object_id']], ['state', 'absent', ['object_id', 'object_id']]]
```
This allows us to safely assume when query is being instead of explicitly checking for it, and no need to build in fail messages as the module catches insufficient args.

**Comment by dagwieers** [comment]
Yup, we can do that. Does not help with the documentation though. We have to add a note in the description of the parameter when that parameter is required. Let's fix this afterwards for the existing and open PRs.

**Comment by dagwieers** [comment]
@jmcgill298 I think we can close this one now.
