### ISSUE TITLE
ACI Port Channel: feature support

### ISSUE THREAD

**Issue by jmcgill298** [datacenter/aci-ansible#59]
The aci_port_channel_interface is missing support for setting the LAG method. I took a look at how the APIC is building this value, and it is concatenating options:
 **"ctrl": "fast-sel-hot-stdby,graceful-conv,susp-individual"**
```
{
    "totalCount": "1",
    "imdata": [
        {
            "lacpLagPol": {
                "attributes": {
                    "ctrl": "fast-sel-hot-stdby,graceful-conv,susp-individual",
                    "descr": "",
                    "dn": "uni/infra/lacplagp-default",
                    "maxLinks": "16",
                    "minLinks": "1",
                    "mode": "off",
                    "name": "default",
                    "nameAlias": "",
                    "ownerKey": "",
                    "ownerTag": ""
                }
            }
        }
    ]
}
```

Since the APIC supports multiple options simultaneously, we should discuss how we want the module to behave:

1. Overwrite the existing `ctrl` values with whatever is supplied by the module.
2. Add to the exising values whatever is missing in proposed.

I vote number 1 as the second option creates added complexity to the diff function and does not provide a solution for removing values from existing.

**Comment by jmcgill298** [comment]
for reference, this is the documenation from the MIM (https://developer.cisco.com/media/mim-ref/MO-lacpIfPol.html)




symmetric-hash | 16u | Symmetric hashing | Symmetric hashing property of PC
susp-individual | 1u | Suspend Individual Port | LACP suspend individual port
graceful-conv | 2u | Graceful Convergence | LACP graceful convergence
load-defer | 4u | Load Defer Member Ports | Load defer
fast-sel-hot-stdby | 8u | Fast Select Hot Standby Ports | LACP fast select for hot standby ports
defaultValue | (1u\|2u\|8u)

**Comment by dagwieers** [comment]
Good call. But can we postpone this until after we have upstreamed the existing stuff first ?

**Comment by jmcgill298** [comment]
absolutely, I raised an issue so we could track it and not forget later.

**Comment by jmcgill298** [comment]
agreed to make `ctrl` a list and be declarative

**Comment by dagwieers** [comment]
Is this something we still want/need to do for v2.4 ? If so, hurry !

**Comment by dagwieers** [comment]
@jmcgill298 Is this still open ? If so, we should move it to upstream.
