### ISSUE TITLE
Rename aci_anp to aci_ap ?

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#87]
Ramses does not understand why fv:Ap is implemented as the aci_anp module. He would rather rename it to aci_ap.

**Comment by jmcgill298** [comment]
So it is fv:Ap, not infra:Ap. The technical name is Application Network Profile, often referred to as ANP or AP. I always preferred AP over ANP, but usually just said App Profile. I like aci_ap as a module name though.

**Comment by dagwieers** [comment]
Yes, that was a typo. Thanks for correcting.

I personally have no preference as I am new to ACI I really don't know what the common terminology is, but I was requested to use the commonly used name instead of the technical names everywhere (so it is easier for customers).

My preference is consistency, but the question really is consistent to what ?
- Internal names, technical names or commonly used names
- And how do we translate that for e.g. bindings (where long names are less user friendly)

**Comment by rsmeyers** [comment]
In general we never talk about an ANP, we talk about Tenant, Ap and EPG's...

**Comment by dagwieers** [comment]
Ok, I guess that's 3 votes out of 5.
