### ISSUE TITLE
Move Needed to here for better discussion

### ISSUE THREAD

**Issue by jmcgill298** [datacenter/aci-ansible#91]
### Needed
- **aci_accessport_block** (infra:PortBlk)
- **aci_accessport_selector** (infra:HPortS)
- **aci_accessport_selector_to_policy_group** (infra:RssAccBaseGrp)
- **aci_intf_profile** (infra:AccPortGrp) *-- not aci_accessport_group*
- **aci_intf_profile_to_accessport_selector** (infra:RssAccPortP)
- **aci_aep_infra** (infra:ProvAcc)
- **aci_aep_to_domain** (infra:RsDomP)
- **aci_aep_to_policy_group** (infra:RsAttEntP)
- **aci_ap** (fv:Ap) *-- not aci_anp*
- ~**aci_bd_to_context** (fv:RsCtx)~
- **aci_domain_to_vlan** (infra:RsVlanNs)
- ~**aci_epg_to_bd** (fv:RsBd)~
- **aci_epg_to_domain** (fv:RsDomAtt)
- **aci_leaf_interface** (infra:AccPortP)
- **aci_phys_domain** (infra:DomP) *-- not aci_domain_profile*
- **aci_switch_leaf_profile** (infra:NodeP)
- **aci_switch_leaf_selector** (infra:LeafS)
- **aci_switch_leaf_selector_node_block** (infra:NodeBlk) *-- not aci_node_block*
- **aci_vlan_encap_block** (fvns:EncapBlk)
- **aci_vlan** (fvns:VlanInstP)
- **aci_vmm_controller** (vmm:CtrlrP)
- **aci_vmm_domain** (vmm:DomP)
- **aci_vrf** (fv:Ctx) *(not aci_context)*

**Update:** Reflect the new binding-naming and remove the bindings with a 1-to-1 mapping.

**Comment by jmcgill298** [comment]
- `aci_bd_context_binding (fv:RsCtx)`
  * BD to VRF are 1-to-1 mappings, not sure this should be separated from the BD module.
- `aci_epg_bd_binding (fv:RsBd)`
  * EPG to BD are 1-to-1 mappings, not sure this should be separated from the EPG module
- `aci_vrf (infra:context) (not aci_context)`
  * aci_vrf (fv:Ctx) (not aci_context)

**Comment by dagwieers** [comment]
@jmcgill298 Ramses and I agree to this, for the 1-to-1 mappings we would still keep it as-is. I guess my list didn't reflect to the 1-to-1 mappings.

**Comment by dagwieers** [comment]
@rsmeyers Should that be **aci_physical_domain_to_vlan** instead of **aci_domain_to_vlan** (given we called it **aci_physical_domain** rather than **aci_domain_profile**).

**Comment by jmcgill298** [comment]
I think physical can be shortened to phys. I think of domains as phys, vmm, l3ext, l2ext

**Comment by rsmeyers** [comment]
As discussed offline let's call it aci_physical_domain or aci_phys_domain, both are good for me

**Comment by dagwieers** [comment]
I moved this back to the Wiki.
