### ISSUE TITLE
More rename proposals (for existing modules)

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#94]
So more proposals. *Speak up now or forever hold your peace.*

- aci_action_rule_profile --> aci_tenant_action_rule_profile
- aci_dhcp_association --> aci_bd_dhcp_association
- aci_epr_policy --> aci_tenant_ep_retention_policy
- aci_fc_policy --> aci_intf_policy_fc
- aci_l2_policy --> aci_intf_policy_l2
- aci_l3out -- *we should not provide this*
- aci_lldp_policy --> aci_intf_policy_lldp
- aci_login_domain --> aci_aaa_login_domain
- aci_mcp --> aci_intf_policy_mcp
- aci_monitoring_policy --> aci_epg_monitoring_policy
- aci_port_channel --> aci_intf_policy_port_channel
- aci_port_security --> aci_intf_policy_port_security
- aci_route_tag_policy --> aci_l3out_route_tag_policy *-- we should not provide this*
- aci_span_dst_group --> aci_tenant_span_dst_group
- aci_span_src_group --> aci_tenant_span_src_group
- aci_subnet --> aci_bd_subnet

**Comment by jmcgill298** [comment]
I disagree about the l3out. Depending on the use case of ACI, the users could be creating them frequently. I would think we should develop several modules supporting l3out/l3ext functionality and contract associations

**Comment by jmcgill298** [comment]
what do you think about changing interface -> intf? That seems to be common

**Comment by rsmeyers** [comment]
intf is Ok for me

**Comment by jmcgill298** [comment]
aci_epr_policy is endpoint retention policy...not sure how many people are using it

**Comment by rsmeyers** [comment]
I understand why you want aci_l3out, but if so, we need 100 more modules..., with the current implementation it's useless...., we need to cover all scenario's then and we'll easily end up with 100+ modules

**Comment by rsmeyers** [comment]
yeah, epr, not sure neither, didn't see it a lot, so if we have to ansiblize it....

**Comment by dagwieers** [comment]
If other's are willing to write them, I don't care ;-)

The legacy stuff most likely is there because someone asked for it before. We probably have to leave it in for backward compatibility.

**Comment by jmcgill298** [comment]
Not sure how we want to go about the span group. We can use 4 mods for the group: aci_tenant_span_src, aci_tenant_span_dst, aci_infra_span_src, and aci_infra_span_dst, or 2 mods and use aci_span_src, aci_span_dst and have a param indicating tenant or infra. I think infra is more useful #57

**Comment by jmcgill298** [comment]
aci_monitoring_policy:

mon:EPGPol Creates a container for monitoring policies associated with the tenant. This allows you to apply tenant-specific policies related to Stats Collection, Stats Export, Callhome/SNMP/Syslog, Event Severities, Fault Severities, and Fault Lifecycles.

**Comment by jmcgill298** [comment]
overall I am fine with the names

**Comment by dagwieers** [comment]
For the SPAN modules, we should then make it clear this is both infra as tenant. I don't mind it's inside of the same module, although it's definitely more clear if we provided 4 modules and keep it separated IMO.

**Comment by dagwieers** [comment]
Probably aci_tenant_monitoring_policy ?

**Comment by dagwieers** [comment]
So **aci_epr_policy** would become **aci_tenant_ep_retention_policy**

**Comment by jmcgill298** [comment]
I think aci_epg_monitoring_policy

**Comment by dagwieers** [comment]
Ok !
